#!/bin/zsh

if ! zsh -c 'echo ${0:A}' &> /dev/null
then
	echo -e "\e[1;31m*** fatal error: zsh too old, upgrade to 4.3.10 plzkthx\e[m"
	exit 6
fi

dizzydir=${0:h:A}

function install_mod() {
	trap 'echo -e "\e[1;31m*** failed to build dependencies - cannot resume\e[m"; exit 1' ERR
	echo -e "\e[1;32m*** building $1\e[m"

	rm -rf $dizzydir/deps_build
	mkdir -p $dizzydir/deps_build
	pushd $dizzydir/deps_build

	modname=$1
	precommands=${2:-true}

	tarball=$(   \
		wget -q -O - 'http://search.cpan.org/search?mode=dist&query='$modname \
		| egrep ${modname//::/-}'-[0-9]' \
		| cut -d\" -f 2 \
		| head -n 1 \
		| sed 's/^/http:\/\/search.cpan.org/' \
		| xargs wget -q -O - \
		| fgrep .tar \
		| cut -d\" -f 2 \
		| sed 's/^/http:\/\/search.cpan.org/' \
	)
	wget $tarball
	tar xf ${tarball:t}
	cd ${modname//::/-}-*/
	if [[ -n $precommands ]]
	then
		${=precommands}
	fi
	perl Makefile.PL PREFIX=$dizzydir/deps_install
	make
	make install
	cd ..

	popd

	echo -e "\e[1;32m*** successfully built $1\e[m"

	trap - ERR
}

function check_mod() {
	wank=$1
	shift
	if perl -I$dizzydir/deps_install/share/perl/ -I$dizzydir/deps_install/lib/perl -M$wank $* -e ''
	then
		echo -e "\e[1;32m*** $wank present\e[m"
		return 0
	else
		echo -e "\e[1;31m*** $wank NOT present\e[m"
		return 1
	fi
}

check_mod OpenGL::Simple \
|| install_mod OpenGL::Simple "patch -Np1 -i $dizzydir/OpenGL-Simple-texturebinding.diff"
check_mod OpenGL::Simple::GLUT \
|| install_mod OpenGL::Simple::GLUT
check_mod Convert::Color \
|| install_mod Convert::Color

export PERL5LIB=${PERL5LIB}:$dizzydir/deps_install/lib/perl:$dizzydir/deps_install/share/perl/
exec $dizzydir/dizzy $*
