#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;

use lib 'lib';
use OpenGL qw(:all);
use Math::Trig;
use Time::HiRes qw(sleep time);
use Dizzy::Handlers;
use Dizzy::Core;
use Dizzy::GLFeatures;
use Dizzy::GLX;

# find out the window id.
my $window_id;
# since XSS gives us an old-style option sometimes, we have to remove it from
# the argument list *before* Getopt chokes on it.
for ($_ = 0; $_ < $#ARGV; $_++) {
	if ($ARGV[$_] eq "-window-id") {
		$window_id = $ARGV[$_ + 1];
		$window_id = oct($window_id) if ($window_id =~ /^0/);
		delete($ARGV[$_ + 1]);
		delete($ARGV[$_]);
	}
}

# sometimes, XSS will give us the information in an environment variable...
if (!$window_id) {
	if (defined($ENV{XSCREENSAVER_WINDOW})) {
		$window_id = $ENV{XSCREENSAVER_WINDOW};
		$window_id = oct($window_id) if ($window_id =~ /^0/);
	}
}

# now we're in trouble. probably user called this directly
if (!$window_id) {
	print STDERR "dizzy-xscreensaver: no window ID to draw on found!\n";
	print STDERR "(did you not read the manual and call this manually instead of dizzy(6)?)\n";
	exit(1);
}

# now we can parse the standard options
my %options = Dizzy::Core::init_arguments();

# initialize OpenGL
if (!Dizzy::GLX::GLX_Setup($window_id)) {
	print STDERR "dizzy-xscreensaver: XLIB error, dying\n";
	exit(1);
}
Dizzy::GLFeatures::update_capabilities();

# initialize dizzy subsystems
Dizzy::Core::init_subsystems(%options);

# main loop
# XXX X event handling
while (1) {
	Dizzy::Handlers::invoke("render");
	Dizzy::GLX::GLX_XEvents();
	glFlush();
	Dizzy::GLX::GLX_SwapBuffers();
}

__END__

=head1 NAME

B<dizzy-xscreensaver> - XScreenSaver compliant variant of dizzy

=head1 SYNOPSIS

B<dizzy-xscreensaver> [I<options>]

=head1 DESCRIPTION

For a description of what Dizzy is and what options it takes, refer to the
L<dizzy> manpage.

This program is a version of Dizzy that can be used as a XScreenSaver hack. It
is not designed to be run directly by users.

=cut
