#!/usr/bin/perl
use strict;
use warnings;

use lib 'lib';
use Dizzy::Textures;

my @textures = Dizzy::Textures::textures();

my $res = $ARGV[0] ||= 256;

foreach my $texture (@textures) {
	print STDERR "rendering $texture->{name}-$res " . " " x 16;
	open(my $outfile, ">", "texture_cache/$texture->{name}-$res");
	for (my $y = 0; $y < $res; $y++) {
		print STDERR sprintf("%s(line %4d/%4d)", "\b" x 16, $y, $res) if (!($y % 16));
		for (my $x = 0; $x < $res; $x++) {
			print $outfile pack("f", $texture->{function}->($x / $res - 0.5, $y / $res - 0.5));
		}
	}
	close($outfile);
	print STDERR "\n";
}
