#!/usr/bin/env perl
# vim:ft=perl
use strict;
use warnings;

use Template::Simple;

# read the functions dir
my @funcs = @ARGV;

# build the template variables
my $data = {
	count => scalar(@funcs),
	functions => [],
};
for (my $i = 0; $i <= $#funcs; $i++) {
	$funcs[$i] =~ /([^\/]+)$/;
	push(@{$data->{functions}}, { id => $i, file => $funcs[$i], name => $1 });
}

# read the template and produce the output file
print ${Template::Simple->new()->render(join("", <STDIN>), $data)};

